name: Digital land smoke test
on:
  schedule:
    - cron: "0 */1 * * *"
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.x'
      - name: Run tests
        id: tests
        run: make test
#        continue-on-error: true
#      - name: Check test failures
#        if: steps.tests.outcome != 'success'
#        run: |
#          make report-error
#          exit -1